import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} px-12 pt-4`}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  )
}


export const dynamic = 'force-dynamic';

export const metadata: Metadata = {
  title: 'server-action-revalidation',
  description: 'Generated by create next app',
}
